### ISSUE TITLE
Migrate from Origami build-service to v3

### ISSUE THREAD

**Issue by chee** [Financial-Times/origami-navigation-service#366]
hello Origami Team! It's me, chee rabbits!

I've noticed this repository still uses Origami Build Service v2, and have opened this issue so we can track migration progress.

Origami's support for Origami Build Service v2 ends on July 2022.

The migration guides are available in the [announcement](https://origami.ft.com/blog/2021/07/01/origami-on-npm-and-how-to-migrate/).

If you have any questions please do not hesitate to ask the Origami Team in [#origami-support](https://financialtimes.slack.com/archives/C02FU5ARJ).

This issue should also be visible on the [migration tracking github project](https://github.com/orgs/Financial-Times/projects/98?fullscreen=true).

**Comment by notlee** [comment]
False alarm: https://github.com/Financial-Times/origami-navigation-service/blob/59c1287fb67afa9868b8bb59f8ff9cad32260577/test/unit/lib/navigation-service.test.js#L31
Done: https://github.com/Financial-Times/origami-navigation-service/pull/352
